# Generated by Django 4.2.1 on 2023-05-05 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tablCamarero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campCamApellidoNombre', models.CharField(help_text='Ingrese un apellido y nombre para el camarero.', max_length=150)),
                ('campFecNacim', models.DateTimeField(help_text='Ingrese la fecha de nacimiento del camarero.')),
                ('campCamActivo', models.CharField(default='SI', help_text='Seleccione si el camarero esta activo.', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tablCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campNombre', models.CharField(help_text='Ingrese un nombre para la categoria.', max_length=100)),
                ('campDescrip', models.CharField(help_text='Ingrese una descripcion para la categoria.', max_length=300, null=True)),
                ('campActivo', models.CharField(default='SI', help_text='Ingrese si la categoria es activa o no.', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tablItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campCartNombre', models.CharField(help_text='Ingrese un nombre para el item del menu.', max_length=100)),
                ('campCartDescrip', models.CharField(help_text='Ingrese una descripcion para el item del menu.', max_length=300)),
                ('campPrecio', models.DecimalField(decimal_places=2, help_text='Ingrese un precio para el item del menu.', max_digits=10)),
                ('campCategoria', models.ForeignKey(help_text='Ingrese una categoria para el item del menu.', on_delete=django.db.models.deletion.PROTECT, to='appRestaurant.tablcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='tablSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campSucNombre', models.CharField(help_text='Ingrese un nombre para la sucursal', max_length=100)),
                ('campSucDireccion', models.CharField(help_text='Ingrese una dirección para la sucursal.', max_length=300, null=True)),
                ('campSucLocalidad', models.CharField(help_text='Ingrese una localidad para la sucrusal.', max_length=30, null=True)),
                ('campSucEmail', models.EmailField(help_text='Ingrese un email para la sucursal.', max_length=254, null=True)),
                ('campSucTelef', models.CharField(help_text='Ingrese un número de telefono para la sucursal.', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tablOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campOrdFecEmis', models.DateField()),
                ('campOrdEstado', models.CharField(help_text='Ingrese el estado de la orden.', max_length=10)),
                ('campOrdCamarero', models.ForeignKey(help_text='Ingrese el camarero que realiza el pedido.', on_delete=django.db.models.deletion.PROTECT, to='appRestaurant.tablcamarero')),
                ('campOrdItem', models.ForeignKey(help_text='Seleccione el item de la orden.', on_delete=django.db.models.deletion.PROTECT, to='appRestaurant.tablitems')),
            ],
        ),
        migrations.CreateModel(
            name='tablMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campMesSigla', models.CharField(help_text='Ingrese una sigla para identificar la mesa.', max_length=15)),
                ('campMesActivo', models.CharField(default='SI', help_text='Seleccione si la mesa esta activa.', max_length=2)),
                ('campMesSuc', models.ForeignKey(help_text='Seleccione la sucursal a cual pertenece la mesa.', on_delete=django.db.models.deletion.PROTECT, to='appRestaurant.tablsucursal')),
            ],
        ),
        migrations.AddField(
            model_name='tablcamarero',
            name='campCamSucursal',
            field=models.ForeignKey(help_text='Seleccione la sucursal donde esta el camarero.', on_delete=django.db.models.deletion.PROTECT, to='appRestaurant.tablsucursal'),
        ),
    ]
